[package]
name = "cargo-flash"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>", "Dominik Boehi <dominik.boehi@gmail.ch>"]
edition = "2018"

[dependencies]
structopt = "0.3.2"
cargo-project = "0.2.2"
failure = "0.1.5"
colored = "1.8.0"
probe = { path = "../probe", version = "0.1.0" }
stlink = { path = "../probe/stlink", version = "0.1.0" }
daplink = { path = "../probe/daplink", version = "0.1.0" }
coresight = { path = "../coresight", version = "0.1.0" }